- name: Mount external hard-drive
  ansible.builtin.import_playbook: hard_drive/hard_drive.yml

- name: Install Transmission
  ansible.builtin.import_playbook: transmission/transmission.yml

- name: Install Borg Backup
  ansible.builtin.import_playbook: borgbackup/borgbackup.yml

- name: Install Kodi
  ansible.builtin.import_playbook: kodi/kodi.yml
