- name: Mount external hard-drive
  hosts: mediaservers
  remote_user: root

  tasks:
    - name: Create the mount point
      ansible.builtin.file:
        path: '{{hard_drive}}'
        state: directory
        mode: 0777

    - name: Mount up device by UUID
      ansible.posix.mount:
        path: '{{hard_drive}}'
        src: UUID=2dd783ff-d530-42ed-b90b-68b843a5a53a
        fstype: ext4
        opts: nofail,x-systemd.automount,x-systemd.device-timeout=5,x-systemd.idle-timeout=1min,noatime
        state: present

- name: Install Transmission
  hosts: mediaservers
  remote_user: root

  tasks:
    - name: Install the latest version of transmission-daemon
      ansible.builtin.apt:
        name: transmission-daemon
        state: latest
        update_cache: yes

    - name: Create the download directory
      ansible.builtin.file:
        path: '{{media}}/Downloads'
        state: directory
        mode: 0777

    - name: Stop transmission-daemon
      ansible.builtin.systemd:
        name: transmission-daemon
        state: stopped

    - name: Copy the settings file
      ansible.builtin.copy:
          src: transmission/settings.json
          dest: /etc/transmission-daemon/settings.json
          owner: debian-transmission
          group: debian-transmission
          mode: '0600'

    - name: Enable transmission-daemon
      ansible.builtin.systemd:
        name: transmission-daemon
        state: started
        enabled: true
