- name: Install Borg Backup
  hosts: mediaservers
  remote_user: root
  gather_facts: false

  tasks:
    - name: Install borg-backup
      ansible.builtin.apt:
        name: borgbackup
        state: present
